version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3100:3100
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3200:3200
    networks:
      - app_network
  prisma:
    image: prismagraphql/prisma
    volumes:
      - ./prisma:/prisma
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PRISMA_SCHEMA: ./prisma/schema.prisma
networks:
  app_network:
    external: true
