version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3100:3100
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3200:3200
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: npx prisma generate
    networks:
      - app_network

networks:
  app_network:
    external: true
